version: '2'
services:
  bot:
    build: ./bot_apiai/
    links:
      - "prov:provision"
    environment:
      - APIAITOKEN="<KEY_HERE>" 
      - ALTCODETOKEN="<KEY_HERE>"
    depends_on:
      - "prov"

  prov:
    build: ./provisioning_service/
    links:
      - "db:database"
    depends_on:
      - "db"
    ports:
      - "8080:8080"

  db:
    image: mongo:3.0.2 
